import { Exo_2 } from "next/font/google";
import "./globals.css";

const exo_2 = Exo_2({ subsets: ["latin"] });

export const metadata = {
  title: "Full-Stack Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`text-xl font-semibold ${exo_2.className}`}>{children}</body>
    </html>
  );
}
